<a href="https://colab.research.google.com/github/MichaelSumagui/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [9]:
import numpy as np
st1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
st2 = np.array([[89],[89],[95]])
total = np.linalg.inv(st1).dot(st2)

print(total)

[[13.]
 [57.]
 [19.]]


Question 2

In [10]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print (B)

Apinv = np.linalg.pinv(A)

x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Question 3

In [12]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

inv_A = np.linalg.inv(A)
print(inv_A)

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
[[ 1.5         1.16666667 -1.        ]
 [-4.         -3.66666667  4.        ]
 [-1.5        -1.5         2.        ]]


In [13]:
A=np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

w,v=np.linalg.eig(A)
print("The eigenvalue/s is/are",w)
print("The eigenvector/s is/are",v)

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s is/are [-1.  3.  2.]
The eigenvector/s is/are [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
