<a href="https://colab.research.google.com/github/MichaelSumagui/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python Program to Inverse

In [10]:
import numpy as np

A = np.array ([[1,2],[4,5]])
invA = (np.linalg.inv(A))
print(invA)

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [11]:
C = np.dot(A,invA)
print(C)

[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


#Python Program to transpose a 3x3 Matrix A = ([6,1,1],[4,-2,5],[2,8,7])

In [16]:
import numpy as np

A = np.array ([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B = np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


#Python Program to inverse a 3x3 Matrix A = ([6,1,1],[4,-2,5],[2,8,7])

In [17]:
import numpy as np 

A = np.array ([[6,1,1],[4,-2,5],[2,8,7]])
B = (np.linalg.inv(A))
print(B)

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
