<a href="https://colab.research.google.com/github/MichaelSumagui/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [3]:
import numpy as np
A = np.array ([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]])
print(A)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


Question 2

In [4]:
import numpy as np
A = np.array ([[1,1,1],[0,1,1],[0,0,1]])
print(A)

[[1 1 1]
 [0 1 1]
 [0 0 1]]


Question 3

In [6]:
import numpy as np
A = np.array ([[1,2,-3],[2,-4,5],[-3,5,1]])
print(A)

[[ 1  2 -3]
 [ 2 -4  5]
 [-3  5  1]]


Question 4

In [7]:
import numpy as np
A = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
B = (np.linalg.inv(A))
print(B)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5

In [10]:
import numpy as np
A = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

5.000000000000001
5


Question 6

In [13]:
import numpy as np
A = np.array ([[5,4,1],[10,9,4],[10,13,15]])
B = np.array ([[3.4],[8.8],[19.2]])

roots = np.linalg.inv(A) @ B
print(roots)

[[0.2]
 [0.4]
 [0.8]]
