<a href="https://colab.research.google.com/github/MichaelSumagui/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.a (WY)

In [23]:
import numpy as np
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])

print("Vector W is",W)
print()
print("Vector Y is",Y)
print()
print("WY")
dot = np.dot(W,Y)
print(dot)
print()

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]

WY
[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]



1.b (Z+Z)

In [6]:
import numpy as np
Z = np.array ([[0,1],[2,3]])

print("Vector Z is", Z)

Vector Z is [[0 1]
 [2 3]]


In [7]:
R = np.add(Z,Z)
R

array([[0, 2],
       [4, 6]])

1.c (3X)

In [22]:
import numpy as np
X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])

print("Vector X is",X)
print()
print("3*X")
print(3*X)

Vector X is [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]

3*X
[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


2.a (YW)^2



In [30]:
import numpy as np
Y = np.array ([[1,2,0],[0,-1,2]])
W = np.array ([[1,-3],[2,-2],[3,1]])

print("Vector Y is",Y)
print()
print("Vector W is",W)
print()
print("(YW)^2")
print(np.dot(Y,W)^2)

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]

(YW)^2
[[ 7 -5]
 [ 6  6]]


2.b (WY - X)

In [21]:
import numpy as np
W = np.array ([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])

print("Vector W is",W)
print()
print("Vector Y is",Y)
print()
print("Vector X is",X)
print()
print("WY-X")
dot = np.dot (W,Y)
print(dot-X)

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]

Vector X is [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]

WY-X
[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


2.c (YW - Z^2)

In [36]:
import numpy as np

Y = np.array ([[1,2,0],[0,-1,2]])
W = np.array ([[1,-3],[2,-2],[3,1]])
Z = np.array ([[0,1],[2,3]])

print("Vector Y is",Y)
print()
print("Vector W is",W)
print()
print("Vector Z is",Z)
print()
print("(YW - Z^2)")
print(np.dot(Y,W)-Z^2)

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]

Vector Z is [[0 1]
 [2 3]]

(YW - Z^2)
[[ 7 -6]
 [ 0  3]]
