<a href="https://colab.research.google.com/github/MichaelSumagui/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [14]:
import numpy as np 

C = np.eye(4)

print("C",C)

C [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 2

In [13]:
import numpy as np

C = np.eye(4)

print(C*2)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question 3

In [1]:
import numpy as np 
A = ([2,7,4])
B = ([3,9,8])

cross = np.cross(A,B)
print(cross)

[20 -4 -3]
