<a href="https://colab.research.google.com/github/MichaelSumagui/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Space Operations

In [2]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [3]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape

(2, 3)

In [4]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
print(pool.shape)
print(pool.size)

(2, 3)
6


In [5]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape
pool.ndim

2

Vector Addition


In [6]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [7]:
R = np.add(A,B)
R

array([ 6, -2])

Vector Subtraction

In [8]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [9]:
R = np.subtract(A,B)
R

array([2, 8])

Vector Scaling

In [10]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

In [11]:
A = np.array([1,5,8,9])
S = np.multiply(5,A)
S

array([ 5, 25, 40, 45])

Vector Cross Product

In [12]:
import numpy as np

A = np.array([2,3])
B = np.array([1,7])

output = np.cross(A,B)
print(output)

11


In [13]:
A = np.array([2,3])
B = np.array([1,7])

cross = np.cross(A,B)
print(cross)

11


In [14]:
A = np.array([2,3,4])
B = np.array([1,7,0])

cross = np.cross(A,B)
print(cross)

[-28   4  11]
